/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "on-surface-variant": "#44474e",
              "inverse-surface": "#313030",
              "surface-container-low": "#f6f3f2",
              "on-secondary-fixed-variant": "#454747",
              "on-tertiary-fixed-variant": "#6e3900",
              "on-secondary": "#ffffff",
              "surface": "#fcf9f8",
              "surface-variant": "#e5e2e1",
              "on-tertiary-container": "#cf7000",
              "primary-fixed": "#d6e3ff",
              "surface-dim": "#dcd9d9",
              "tertiary": "#160700",
              "background": "#fcf9f8",
              "error-container": "#ffdad6",
              "surface-container-high": "#eae7e7",
              "surface-tint": "#465f88",
              "on-primary-fixed": "#001b3d",
              "outline-variant": "#c4c6cf",
              "inverse-on-surface": "#f3f0ef",
              "secondary-fixed": "#e2e2e2",
              "on-error": "#ffffff",
              "tertiary-container": "#371a00",
              "surface-bright": "#fcf9f8",
              "on-primary-container": "#708ab5",
              "inverse-primary": "#aec7f6",
              "on-surface": "#1c1b1b",
              "on-primary-fixed-variant": "#2d476f",
              "outline": "#74777f",
              "primary": "#000a1e",
              "tertiary-fixed-dim": "#ffb77d",
              "tertiary-fixed": "#ffdcc3",
              "on-secondary-fixed": "#1a1c1c",
              "surface-container-highest": "#e5e2e1",
              "secondary": "#5d5f5f",
              "error": "#ba1a1a",
              "secondary-fixed-dim": "#c6c6c7",
              "on-error-container": "#93000a",
              "on-secondary-container": "#5f6161",
              "surface-container": "#f0eded",
              "primary-container": "#002147",
              "on-tertiary": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "on-background": "#1c1b1b",
              "on-primary": "#ffffff",
              "primary-fixed-dim": "#aec7f6",
              "secondary-container": "#dcdddd",
              "on-tertiary-fixed": "#2f1500",
              "brand-orange": "#FF8C00"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          "spacing": {
              "margin-desktop": "64px",
              "container-max": "1280px",
              "stack-lg": "48px",
              "stack-md": "24px",
              "base": "8px",
              "stack-sm": "12px",
              "gutter": "24px",
              "margin-mobile": "20px"
          },
          "fontFamily": {
              "body-lg": ["Inter", "sans-serif"],
              "label-md": ["Inter", "sans-serif"],
              "headline-md": ["Montserrat", "sans-serif"],
              "headline-lg-mobile": ["Montserrat", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-xl": ["Montserrat", "sans-serif"],
              "headline-lg": ["Montserrat", "sans-serif"],
              "button": ["Montserrat", "sans-serif"],
              "sans": ["Inter", "sans-serif"],
              "heading": ["Montserrat", "sans-serif"]
          },
          "fontSize": {
              "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
              "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "headline-lg-mobile": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "button": ["16px", { "lineHeight": "20px", "fontWeight": "700" }]
          }
      },
  },
  plugins: [],
}
